// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies";
    extern const char* const UnityCopyright = "(c) 2005-2023 Unity Technologies. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/jenkins/sharedspace/ra_2021.3";

    extern const char* const UnityVersion = "2021.3.24f1c1";
    extern const char* const UnityVersionDigits = "2021.3.24";
    extern const char* const UnityVersionSuffix = "f1c1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 24;
    extern const bool UnityVersionIsBeta = 1;

    extern const char* const UnityVersionUnderHash = "2021.3.24f1c1_efaefd9b44a9";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.3.24f1c1.git..15707901_efaefd9b44a9";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.3.24f1c1 (efaefd9b44a9)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 15707901;

    extern const UInt64 UnityVersionDate = 1684402386;
    extern const char* const UnityVersionBranch = "origin/2021.3/china_unity/release";
    extern const char* const UnityVersionDisplay = "2021.3.24f1c1.git.origin/2021.3/china_unity/release.15707901";
    extern const char* const UnityVersionDisplay_Verbose = "2021.3.24f1c1.git.origin/2021.3/china_unity/release.15707901";
    extern const char* const UnityVersionRevision = "efaefd9b44a9";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.3.24f1c1 (efaefd9b44a9)";
    extern const wchar_t* const L_UnityVersion = L"2021.3.24f1c1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies"
    #define UNITY_COPYRIGHT "(c) 2005-2023 Unity Technologies. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 24
    #define UNITY_IS_BETA 1
    #define UNITY_VERSION_UNDER_HASH "2021.3.24f1c1_efaefd9b44a9"
    #define UNITY_VERSION_PARENS_HASH "2021.3.24f1c1 (efaefd9b44a9)"
    #define UNITY_VERSION_BLD 15707901
    #define UNITY_VERSION_WIN "2021.3.24.15707901"

#endif // !RC_INVOKED
