// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies";
    extern const char* const UnityCopyright = "(c) 2005-2023 Unity Technologies. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2021.3.29f1";
    extern const char* const UnityVersionDigits = "2021.3.29";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 29;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.3.29f1_204d6dc9ae1c";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.3.29f1_204d6dc9ae1c";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.3.29f1 (204d6dc9ae1c)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 2116973;

    extern const UInt64 UnityVersionDate = 1689640209;
    extern const char* const UnityVersionBranch = "2021.3/staging";
    extern const char* const UnityVersionDisplay = "2021.3.29f1";
    extern const char* const UnityVersionDisplay_Verbose = "2021.3.29f1.git.2116973";
    extern const char* const UnityVersionRevision = "204d6dc9ae1c";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.3.29f1 (204d6dc9ae1c)";
    extern const wchar_t* const L_UnityVersion = L"2021.3.29f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies"
    #define UNITY_COPYRIGHT "(c) 2005-2023 Unity Technologies. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 29
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.3.29f1_204d6dc9ae1c"
    #define UNITY_VERSION_PARENS_HASH "2021.3.29f1 (204d6dc9ae1c)"
    #define UNITY_VERSION_BLD 2116973
    #define UNITY_VERSION_WIN "2021.3.29.2116973"

#endif // !RC_INVOKED
