
/*******************************************************
 * Code Generated By AirFramework
 * DateTime : 2023/7/31 11:17:05
 * UVersion : 2021.3.24f1c1
 *******************************************************/
using UnityEngine;

namespace AirFramework.Utility.RefBuild.Cache
{
    public partial class CounterPanel : UnityEngine.MonoBehaviour
    {
        public UnityEngine.CanvasGroup CounterPanel_CanvasGroup { get; set; } = default;
        public AirFramework.MV.RefBuild.BindableProperty<System.Single> CounterPanel_CanvasGroup_alpha {get;set;}=default;


        public void InitRefs()
        {
            CounterPanel_CanvasGroup = GetComponent<UnityEngine.CanvasGroup>();
            CounterPanel_CanvasGroup_alpha = new AirFramework.MV.RefBuild.BindableProperty<System.Single>(()=>CounterPanel_CanvasGroup.alpha,(x)=>CounterPanel_CanvasGroup.alpha=x,false);

        }

        
        private void Awake()
        {
            InitRefs();
        }

    }
    
}
