
/*******************************************************
 * Code Generated By AirFramework
 * DateTime : 2023/7/31 10:48:28
 * UVersion : 2021.3.24f1c1
 *******************************************************/
using UnityEngine;
using AirFramework.MV.RefBuild;

namespace AirFramework.Utility.RefBuild.Cache
{
    public partial class CounterPanel : UnityEngine.MonoBehaviour
    {
        public UnityEngine.CanvasGroup CounterPanel_CanvasGroup_0 { get; set; } = default;
        public BindableProperty<System.Single> CounterPanel_CanvasGroup_0_alpha {get;set;}=default;


        public void InitRefs()
        {
            CounterPanel_CanvasGroup_0 = GetComponent<UnityEngine.CanvasGroup>();
            CounterPanel_CanvasGroup_0_alpha = new BindableProperty<System.Single>(()=>CounterPanel_CanvasGroup_0.alpha,(x)=>CounterPanel_CanvasGroup_0.alpha=x,false);

        }

        
        private void Awake()
        {
            InitRefs();
        }

    }
    
}
