
/*******************************************************
 * Code Generated By AirFramework
 * DateTime : 2023/8/27 13:02:03
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;

namespace AirFramework.MV.RefBuild.Cache
{
    public partial class Cube : UnityEngine.MonoBehaviour
    {
        public UnityEngine.Transform Cube_Transform { get; set; } = default;
        public AirFramework.MV.RefBuild.BindableProperty<UnityEngine.Vector3> Cube_Transform_position {get;set;}=default;


        public void InitRefs()
        {
            Cube_Transform = GetComponent<UnityEngine.Transform>();
            Cube_Transform_position = new AirFramework.MV.RefBuild.BindableProperty<UnityEngine.Vector3>(()=>Cube_Transform.position,(x)=>Cube_Transform.position=x,false);

        }

        
        private void Awake()
        {
            InitRefs();
        }

    }
    
}
